name: 'setup-node'
description: 'setup node using mise'

runs:
  using: 'composite'
  steps:
    - name: Setup Node and npm with mise
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151
      with:
        cache: true
        install: true
        working_directory: front

    - name: Cache node modules
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: front/node_modules
        key: npm-${{ runner.os }}-modules-${{ hashFiles('front/package-lock.json') }}
