name: 'setup-node'
description: 'setup node using mise'

runs:
  using: 'composite'
  steps:
    - name: Setup Node and npm with mise
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151
      with:
        cache: true
        install: true

    - name: Cache node modules
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: front/node_modules
        key: npm-${{ runner.os }}-modules-${{ hashFiles('front/package-lock.json') }}
