name: 'setup-node'
description: 'setup node using mise'

runs:
  using: 'composite'
  steps:
    - name: Setup Node and npm with mise
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151
      with:
        cache: true
        install: true

    - name: Cache node modules
      uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6
      with:
        path: front/node_modules
        key: npm-${{ runner.os }}-modules-${{ hashFiles('front/package-lock.json') }}
