// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "email": "contact@zide.fr"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/account": {
            "post": {
                "description": "Create a new account with the provided parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Create an account",
                "parameters": [
                    {
                        "description": "Account parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.AccountCreateDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request - Code can be: ERR_INVALID_EMAIL_FORMAT, ERR_INVALID_PASSWORD_FORMAT, or ERR_EMAIL_ALREADY_EXISTS",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update own account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Update my account",
                "parameters": [
                    {
                        "description": "Account parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.AccountUpdateDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.AccountResponseDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Code can be: ERR_USERNAME_ALREADY_TAKEN, ERR_INVALID_PASSWORD_FORMAT, or ERR_INVALID_COLOR_FORMAT",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                },
                "security": [
                    {
                        "AccessTokenCookie": []
                    }
                ]
            }
        },
        "/api/v1/account/avatar": {
            "patch": {
                "description": "UploadAvatar the avatar image of the current user",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Upload Avatar",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Avatar image file",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                },
                "security": [
                    {
                        "AccessTokenCookie": []
                    }
                ]
            }
        },
        "/api/v1/account/forgot-password": {
            "post": {
                "description": "Send a password reset email to the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Forgot Password",
                "parameters": [
                    {
                        "description": "Email for password reset",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.ForgotPasswordDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request - Code can be: ERR_PASSWORD_RESET_TOO_FREQUENT",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                }
            }
        },
        "/api/v1/account/me": {
            "get": {
                "description": "Get the account information of the current user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Get My Account",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.AccountResponseDto"
                        }
                    }
                },
                "security": [
                    {
                        "AccessTokenCookie": []
                    }
                ]
            }
        },
        "/api/v1/account/reset-password": {
            "post": {
                "description": "Reset password using reset token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Reset Password",
                "parameters": [
                    {
                        "description": "Reset token and new password",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.ResetPasswordDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request - Code can be: ERR_INVALID_PASSWORD_FORMAT, ERR_INVALID_RESET_TOKEN, or ERR_RESET_TOKEN_EXPIRED",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                },
                "security": [
                    {
                        "AccessTokenCookie": []
                    }
                ]
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Refresh access token using refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Refresh access token",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/signin": {
            "post": {
                "description": "Sign in with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Sign in",
                "parameters": [
                    {
                        "description": "Sign in parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/signin.SigninDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/signin.TokenResponseDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Code can be: ERR_INVALID_IDENTIFIER_OR_PASSWORD",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/status": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Status Check",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/{provider}/url": {
            "get": {
                "tags": [
                    "Authentication"
                ],
                "summary": "Get redirect URL for OAuth provider",
                "parameters": [
                    {
                        "enum": [
                            "google",
                            "github",
                            "discord"
                        ],
                        "type": "string",
                        "description": "OAuth provider",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "URL to return to after OAuth",
                        "name": "returnUrl",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OAuth URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                }
            }
        },
        "/api/v1/availabilities/{availabilityId}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Availability"
                ],
                "summary": "Delete an availability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Availability ID",
                        "name": "availabilityId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request - Code can be: ERR_AVAILABILITY_NOT_FOUND, ERR_AVAILABILITY_ACCESS_DENIED, ERR_EVENT_ACCESS_DENIED, or ERR_EVENT_ENDED",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Availability"
                ],
                "summary": "Update an availability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Availability ID",
                        "name": "availabilityId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Availability parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/availability.AvailabilityUpdateDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/availability.AvailabilityResponseDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Code can be: ERR_AVAILABILITY_NOT_FOUND, ERR_AVAILABILITY_ACCESS_DENIED, ERR_EVENT_NOT_FOUND, ERR_EVENT_ENDED, ERR_EVENT_ACCESS_DENIED, ERR_EVENT_START_AFTER_END, ERR_AVAILABILITY_DURATION_TOO_SHORT, ERR_AVAILABILITY_INVALID_TIME_INTERVAL, ERR_AVAILABILITY_START_BEFORE_EVENT, or ERR_AVAILABILITY_END_AFTER_EVENT",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/v1/events": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Get user events",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/lib.Pagination-event_EventListItemDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Create an event",
                "parameters": [
                    {
                        "description": "Event parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/event.EventCreateDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/event.EventCreateResponseDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Code can be: ERR_EVENT_START_AFTER_END, ERR_EVENT_START_BEFORE_TODAY, or ERR_EVENT_DURATION_TOO_SHORT",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/v1/events/{eventId}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Get event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event Id",
                        "name": "eventId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/event.EventFullResponseDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Code can be: ERR_EVENT_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Update an event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event Id",
                        "name": "eventId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Event parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/event.EventUpdateDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request - Code can be: ERR_EVENT_NOT_FOUND, ERR_EVENT_ACCESS_DENIED, ERR_EVENT_START_AFTER_END, ERR_EVENT_DURATION_TOO_SHORT, ERR_EVENT_START_BEFORE_TODAY, or ERR_VALIDATED_SLOT_CANNOT_BE_MODIFIED",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/v1/events/{eventId}/availability": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Availability"
                ],
                "summary": "Create an availability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "eventId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Availability parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/availability.AvailabilityCreateDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/availability.AvailabilityResponseDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Code can be: ERR_EVENT_NOT_FOUND, ERR_EVENT_ENDED, ERR_EVENT_ACCESS_DENIED, ERR_EVENT_START_AFTER_END, ERR_AVAILABILITY_DURATION_TOO_SHORT, ERR_AVAILABILITY_INVALID_TIME_INTERVAL, ERR_AVAILABILITY_START_BEFORE_EVENT, or ERR_AVAILABILITY_END_AFTER_EVENT",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/v1/events/{eventId}/join": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Join event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event Id",
                        "name": "eventId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/event.EventFullResponseDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Code can be: ERR_EVENT_NOT_FOUND, ERR_EVENT_ALREADY_JOINED, or ERR_EVENT_ENDED",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/v1/events/{eventId}/profile": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Update event profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event Id",
                        "name": "eventId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Event profile parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/event.EventProfileDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request - Code can be: ERR_EVENT_NOT_FOUND or ERR_INVALID_COLOR_FORMAT",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/v1/events/{eventId}/summary": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Get event summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event Id",
                        "name": "eventId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/event.EventBasicResponseDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Code can be: ERR_EVENT_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                }
            }
        },
        "/api/v1/slots/{slotId}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Slot"
                ],
                "summary": "Remove a validated slot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slot Id",
                        "name": "slotId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request - Code can be: ERR_SLOT_NOT_FOUND or ERR_EVENT_ACCESS_DENIED",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/v1/slots/{slotId}/confirm": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Slot"
                ],
                "summary": "Confirm a slot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slot Id",
                        "name": "slotId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Confirm Slot parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/slot.ConfirmSlotDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/slot.SlotResponseDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Code can be: ERR_SLOT_NOT_FOUND, ERR_EVENT_ACCESS_DENIED, ERR_EVENT_ENDED, ERR_SLOT_INVALID_STARTS_AT, or ERR_SLOT_INVALID_ENDS_AT",
                        "schema": {
                            "$ref": "#/definitions/helpers.ApiError"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/v1/events/{eventId}/sse": {
            "get": {
                "description": "Establishes a Server-Sent Events connection to receive real-time updates for a specific event",
                "tags": [
                    "SSE"
                ],
                "summary": "Connect to SSE for event updates",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "eventId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Stream of slot update arrays",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/sse.SSESlotUpdateMessage"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid event ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "User not authenticated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "account.AccountCreateDto": {
            "type": "object",
            "required": [
                "email",
                "language",
                "password",
                "termsAccepted",
                "termsVersion",
                "timeZone"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 320,
                    "minLength": 6
                },
                "language": {
                    "enum": [
                        "en",
                        "fr"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/constants.AccountLanguage"
                        }
                    ]
                },
                "password": {
                    "type": "string",
                    "maxLength": 100
                },
                "termsAccepted": {
                    "type": "boolean"
                },
                "termsVersion": {
                    "type": "string"
                },
                "timeZone": {
                    "type": "string"
                }
            }
        },
        "account.AccountProviderDto": {
            "type": "object",
            "properties": {
                "provider": {
                    "$ref": "#/definitions/constants.Provider"
                }
            }
        },
        "account.AccountResponseDto": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "language": {
                    "$ref": "#/definitions/constants.AccountLanguage"
                },
                "providers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/account.AccountProviderDto"
                    }
                },
                "timeZone": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "account.AccountUpdateDto": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "maxLength": 320,
                    "minLength": 6
                },
                "language": {
                    "enum": [
                        "en",
                        "fr"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/constants.AccountLanguage"
                        }
                    ]
                },
                "password": {
                    "type": "string",
                    "maxLength": 100
                },
                "termsAccepted": {
                    "type": "boolean"
                },
                "termsVersion": {
                    "type": "string"
                },
                "timeZone": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 3
                }
            }
        },
        "account.ForgotPasswordDto": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 320,
                    "minLength": 6
                }
            }
        },
        "account.ResetPasswordDto": {
            "type": "object",
            "required": [
                "password",
                "token"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 100
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "availability.AvailabilityCreateDto": {
            "type": "object",
            "required": [
                "endsAt",
                "startsAt"
            ],
            "properties": {
                "endsAt": {
                    "type": "string"
                },
                "startsAt": {
                    "type": "string"
                }
            }
        },
        "availability.AvailabilityResponseDto": {
            "type": "object",
            "properties": {
                "endsAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "startsAt": {
                    "type": "string"
                }
            }
        },
        "availability.AvailabilityUpdateDto": {
            "type": "object",
            "properties": {
                "endsAt": {
                    "type": "string"
                },
                "startsAt": {
                    "type": "string"
                }
            }
        },
        "constants.AccountLanguage": {
            "type": "string",
            "enum": [
                "en",
                "fr"
            ],
            "x-enum-varnames": [
                "ACCOUNT_LANGUAGE_EN",
                "ACCOUNT_LANGUAGE_FR"
            ]
        },
        "constants.EventStatus": {
            "type": "string",
            "enum": [
                "IN_DECISION",
                "UPCOMING",
                "FINISHED"
            ],
            "x-enum-varnames": [
                "EVENT_STATUS_IN_DECISION",
                "EVENT_STATUS_UPCOMING",
                "EVENT_STATUS_FINISHED"
            ]
        },
        "constants.Provider": {
            "type": "string",
            "enum": [
                "google",
                "discord",
                "github"
            ],
            "x-enum-varnames": [
                "PROVIDER_GOOGLE",
                "PROVIDER_DISCORD",
                "PROVIDER_GITHUB"
            ]
        },
        "event.EventBasicResponseDto": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "endsAt": {
                    "type": "string"
                },
                "hours": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "minutes": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "startsAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/constants.EventStatus"
                }
            }
        },
        "event.EventCreateDto": {
            "type": "object",
            "required": [
                "endsAt",
                "name",
                "startsAt"
            ],
            "properties": {
                "days": {
                    "type": "integer",
                    "minimum": 0
                },
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "endsAt": {
                    "type": "string"
                },
                "hours": {
                    "type": "integer",
                    "maximum": 23,
                    "minimum": 0
                },
                "minutes": {
                    "type": "integer",
                    "maximum": 59,
                    "minimum": 0
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 5
                },
                "startsAt": {
                    "type": "string"
                }
            }
        },
        "event.EventCreateResponseDto": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "endsAt": {
                    "type": "string"
                },
                "hours": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "minutes": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "$ref": "#/definitions/event.EventOwnerDto"
                },
                "startsAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/constants.EventStatus"
                }
            }
        },
        "event.EventFullResponseDto": {
            "type": "object",
            "properties": {
                "availabilities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Availability"
                    }
                },
                "days": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "endsAt": {
                    "type": "string"
                },
                "hours": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "minutes": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "$ref": "#/definitions/event.EventOwnerDto"
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/event.EventParticipantDto"
                    }
                },
                "slots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Slot"
                    }
                },
                "startsAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/constants.EventStatus"
                }
            }
        },
        "event.EventListItemDto": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "endsAt": {
                    "type": "string"
                },
                "hours": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "minutes": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "startsAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/constants.EventStatus"
                }
            }
        },
        "event.EventOwnerDto": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "event.EventParticipantDto": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "event.EventProfileDto": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                }
            }
        },
        "event.EventUpdateDto": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "integer",
                    "minimum": 0
                },
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "endsAt": {
                    "type": "string"
                },
                "hours": {
                    "type": "integer",
                    "maximum": 23,
                    "minimum": 0
                },
                "minutes": {
                    "type": "integer",
                    "maximum": 59,
                    "minimum": 0
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 5
                },
                "startsAt": {
                    "type": "string"
                }
            }
        },
        "helpers.ApiError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "lib.Pagination-event_EventListItemDto": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/event.EventListItemDto"
                    }
                },
                "limit": {
                    "type": "integer",
                    "maximum": 50,
                    "minimum": 1
                },
                "page": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.Availability": {
            "type": "object",
            "properties": {
                "endsAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "startsAt": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "model.Slot": {
            "type": "object",
            "properties": {
                "endsAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isValidated": {
                    "type": "boolean"
                },
                "startsAt": {
                    "type": "string"
                }
            }
        },
        "signin.SigninDto": {
            "type": "object",
            "required": [
                "identifier",
                "password"
            ],
            "properties": {
                "identifier": {
                    "type": "string",
                    "maxLength": 320,
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "signin.TokenResponseDto": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "slot.ConfirmSlotDto": {
            "type": "object",
            "required": [
                "endsAt",
                "startsAt"
            ],
            "properties": {
                "endsAt": {
                    "type": "string"
                },
                "startsAt": {
                    "type": "string"
                }
            }
        },
        "slot.SlotResponseDto": {
            "type": "object",
            "properties": {
                "endsAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isValidated": {
                    "type": "boolean"
                },
                "startsAt": {
                    "type": "string"
                }
            }
        },
        "sse.SSESlotUpdateMessage": {
            "type": "object",
            "properties": {
                "endsAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isValidated": {
                    "type": "boolean"
                },
                "startsAt": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "AccessTokenCookie": {
            "description": "Enter your bearer token in the format **Bearer \u0026lt;token\u0026gt;**",
            "type": "apiKey",
            "name": "access_token",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0b",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "SlotFinder API",
	Description:      "SlotFinder API Doc",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
