name: 'setup-go'
description: 'Setup Go environment'

runs:
  using: 'composite'
  steps:
    - name: Extract Go version from go.mod
      shell: bash
      working-directory: ${{ env.BACK_FOLDER }}
      run: |
        GO_VERSION=$(grep -E "^go [0-9]+\.[0-9]+(\.[0-9]+)?" go.mod | awk '{print $2}')
        echo "GO_VERSION=${GO_VERSION}" >> $GITHUB_ENV

    - name: Setup Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
        cache-dependency-path: ${{ env.BACK_FOLDER }}/go.sum
