name: 'setup-go'
description: 'Setup Go environment'

runs:
  using: 'composite'
  steps:
    - name: Extract Go version from go.mod
      shell: bash
      run: |
        GO_VERSION=$(grep -E "^go [0-9]+\.[0-9]+(\.[0-9]+)?" back/go.mod | awk '{print $2}')
        echo "GO_VERSION=${GO_VERSION}" >> $GITHUB_ENV

    - name: Setup Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
        cache-dependency-path: back/go.sum
