name: 'setup-go'
description: 'Setup Go environment using mise'

runs:
  using: 'composite'
  steps:
    - name: Setup Go with mise
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151
      with:
        cache: true
        install: true
        working_directory: back
