package constants

import (
	"errors"
	"net/http"
)

type CustomError struct {
	Err        error // Custom error code
	StatusCode *int  // Http Status Code, keep nil for default status code 400
}

func err(code string, httpStatus int) CustomError {
	var httpStatusPtr *int
	if httpStatus != 0 {
		httpStatusPtr = &httpStatus
	}

	return CustomError{errors.New(code), httpStatusPtr}
}

var (
	// Generic
	ERR_SERVER_ERROR = err("SERVER_ERROR", 0)
	// Auth
	ERR_NOT_AUTHENTICATED              = err("NOT_AUTHENTICATED", http.StatusUnauthorized)
	ERR_TOKEN_INVALID                  = err("TOKEN_INVALID", http.StatusUnauthorized)
	ERR_TOKEN_EXPIRED                  = err("TOKEN_EXPIRED", http.StatusUnauthorized)
	ERR_PROVIDER_CONNECTION_FAILED     = err("PROVIDER_CONNECTION_FAILED", 0)
	ERR_INVALID_IDENTIFIER_OR_PASSWORD = err("INVALID_IDENTIFIER_OR_PASSWORD", http.StatusUnauthorized)
	// Account
	ERR_INVALID_EMAIL_FORMAT   = err("INVALID_EMAIL_FORMAT", 0)
	ERR_USERNAME_ALREADY_TAKEN = err("USERNAME_ALREADY_TAKEN", 0)
	ERR_EMAIL_ALREADY_EXISTS   = err("EMAIL_ALREADY_EXISTS", 0)
	ERR_USERNAME_MISSING       = err("USERNAME_MISSING", 0)
	// Event
	ERR_EVENT_ACCESS_DENIED      = err("EVENT_ACCESS_DENIED", http.StatusForbidden)
	ERR_EVENT_NOT_FOUND          = err("EVENT_NOT_FOUND", http.StatusNotFound)
	ERR_EVENT_START_AFTER_END    = err("EVENT_START_AFTER_END", 0)
	ERR_EVENT_START_BEFORE_TODAY = err("EVENT_START_NOT_TODAY", 0)
	ERR_EVENT_DURATION_TOO_SHORT = err("EVENT_DURATION_TOO_SHORT", 0)
	ERR_EVENT_ALREADY_JOINED     = err("EVENT_ALREADY_JOINED", 0)
	ERR_EVENT_ENDED              = err("EVENT_ENDED", 0)
	// Availability
	ERR_AVAILABILITY_ACCESS_DENIED         = err("ERR_AVAILABILITY_ACCESS_DENIED", http.StatusForbidden)
	ERR_AVAILABILITY_DURATION_TOO_SHORT    = err("ERR_AVAILABILITY_DURATION_TOO_SHORT", 0)
	ERR_AVAILABILITY_START_BEFORE_EVENT    = err("ERR_AVAILABILITY_START_BEFORE_EVENT", 0)
	ERR_AVAILABILITY_END_AFTER_EVENT       = err("ERR_AVAILABILITY_END_AFTER_EVENT", 0)
	ERR_AVAILABILITY_INVALID_TIME_INTERVAL = err("ERR_AVAILABILITY_INVALID_TIME_INTERVAL", 0)
	ERR_AVAILABILITY_NOT_FOUND             = err("ERR_AVAILABILITY_NOT_FOUND", http.StatusNotFound)
	// Slot
	ERR_SLOT_NOT_FOUND         = err("SLOT_NOT_FOUND", http.StatusNotFound)
	ERR_SLOT_INVALID_STARTS_AT = err("SLOT_INVALID_STARTS_AT", 0)
	ERR_SLOT_INVALID_ENDS_AT   = err("SLOT_INVALID_ENDS_AT", 0)
	// Misc
	ERR_INVALID_COLOR_FORMAT = err("INVALID_COLOR_FORMAT", 0)
)

var CUSTOM_ERRORS = []CustomError{
	// Generic
	ERR_SERVER_ERROR,
	// Auth
	ERR_NOT_AUTHENTICATED,
	ERR_TOKEN_INVALID,
	ERR_TOKEN_EXPIRED,
	ERR_INVALID_IDENTIFIER_OR_PASSWORD,
	// Account
	ERR_INVALID_EMAIL_FORMAT,
	ERR_USERNAME_ALREADY_TAKEN,
	ERR_EMAIL_ALREADY_EXISTS,
	ERR_USERNAME_MISSING,
	// Event
	ERR_EVENT_ACCESS_DENIED,
	ERR_EVENT_NOT_FOUND,
	ERR_EVENT_START_AFTER_END,
	ERR_EVENT_START_BEFORE_TODAY,
	ERR_EVENT_DURATION_TOO_SHORT,
	ERR_EVENT_ALREADY_JOINED,
	ERR_EVENT_ENDED,
	// Availability
	ERR_AVAILABILITY_ACCESS_DENIED,
	ERR_AVAILABILITY_DURATION_TOO_SHORT,
	ERR_AVAILABILITY_START_BEFORE_EVENT,
	ERR_AVAILABILITY_END_AFTER_EVENT,
	ERR_AVAILABILITY_INVALID_TIME_INTERVAL,
	ERR_AVAILABILITY_NOT_FOUND,
	// Slot
	ERR_SLOT_NOT_FOUND,
	ERR_SLOT_INVALID_STARTS_AT,
	ERR_SLOT_INVALID_ENDS_AT,
	// Misc
	ERR_INVALID_COLOR_FORMAT,
}

var CUSTOM_ERRORS_MAP = func() map[string]CustomError {
	m := make(map[string]CustomError)
	for _, ce := range CUSTOM_ERRORS {
		m[ce.Err.Error()] = ce
	}
	return m
}()
