package constants

import "errors"

func err(code string) error {
	return errors.New(code)
}

var (
	// Generic
	ERR_SERVER_ERROR = err("SERVER_ERROR")
	// Auth
	// Account
	ERR_INVALID_EMAIL_FORMAT   = err("INVALID_EMAIL_FORMAT")
	ERR_USERNAME_ALREADY_TAKEN = err("USERNAME_ALREADY_TAKEN")
	ERR_EMAIL_ALREADY_EXISTS   = err("EMAIL_ALREADY_EXISTS")
	// Event
	ERR_EVENT_START_AFTER_END = err("EVENT_START_AFTER_END")
	ERR_EVENT_START_NOT_TODAY = err("EVENT_START_NOT_TODAY")
)

var CUSTOM_ERRORS = []error{
	// Generic
	ERR_SERVER_ERROR,
	// Auth
	// Account
	ERR_INVALID_EMAIL_FORMAT,
	ERR_USERNAME_ALREADY_TAKEN,
	ERR_EMAIL_ALREADY_EXISTS,
	// Event
	ERR_EVENT_START_AFTER_END,
	ERR_EVENT_START_NOT_TODAY,
}
