name: Front Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  merge_group:
    branches: ["main"]

env:
  FRONT_FOLDER: ./front

jobs:
  detect-changes:
    name: Detect Front Changes
    runs-on: ubuntu-latest
    outputs:
      front: ${{ steps.filter.outputs.front }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Check for front file changes
        uses: dorny/paths-filter@d1c1ffe0248fe513906c8e24db8ea791d46f8590 # v3.0.3
        id: filter
        with:
          filters: |
            front:
              - "front/**"
              - ".github/workflows/front-build.yaml"
              - ".github/actions/setup-node/**"
              - "Makefile"

  install:
    name: Front Install package
    needs: detect-changes
    if: needs.detect-changes.outputs.front == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Check package-lock.json
        working-directory: ${{ env.FRONT_FOLDER }}
        run: npm run package:check

      - name: Install package
        working-directory: ${{ env.FRONT_FOLDER }}
        run: npm ci

  lint:
    name: Front Lint code
    needs: [detect-changes, install]
    if: needs.detect-changes.outputs.front == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Run lint
        working-directory: ${{ env.FRONT_FOLDER }}
        run: npm run lint

  test:
    name: Front Test
    needs: [detect-changes, install]
    if: needs.detect-changes.outputs.front == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Run Playwright install
        working-directory: ${{ env.FRONT_FOLDER }}
        run: npx playwright install

      - name: Run test
        working-directory: ${{ env.FRONT_FOLDER }}
        run: npm run test

  build:
    name: Front Build
    needs: [detect-changes, install]
    if: needs.detect-changes.outputs.front == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Run build
        working-directory: ${{ env.FRONT_FOLDER }}
        run: npm run build

  storybook-build:
    name: Front Build Storybook
    needs: [detect-changes, install]
    if: needs.detect-changes.outputs.front == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Run build
        working-directory: ${{ env.FRONT_FOLDER }}
        run: npm run build:storybook

  chromatic:
    name: Run Chromatic
    needs: [detect-changes, install]
    if: needs.detect-changes.outputs.front == 'true' && ((github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') || (github.event_name == 'push' && github.ref == 'refs/heads/main'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Filter changed paths
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: changes
        with:
          filters: |
            ui:
              - 'front/src/ui/**'
      - name: Setup Node
        if: steps.changes.outputs.ui == 'true'
        uses: ./.github/actions/setup-node
      - name: Run Chromatic
        if: steps.changes.outputs.ui == 'true'
        uses: chromaui/action@0794e6939fe40ce46a88963f818092afc427da5b # v15
        with:
          buildScriptName: "build:storybook"
          workingDir: "front"
          onlyChanged: false
          zip: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: "main"
